name: Build and test of Java Project

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: echo a String
      run: echo "Hello World"
      
    - name: echo a CD
      run: |
            mkdir pepe
            cd pepe
            ls >> gg.txt
            
    - name: echo a tail
      run: |
            mkdir javier
            cd javier
            touch holas.txt
            ls >> hola.txt
            tail hola.txt
            
    - name: echo a cat
      run: |
            mkdir jose
            cd jose
            cat > celu.txt 
            
    - name: echo a pwd
      run: |   
            pwd
            
    
    - name: echo a cp
      run: |
            mkdir heredia
            cd heredia
            touch pepas.txt
            cp pepas.txt /home/runner/work/Heredia-Benjamin-6-11/Heredia-Benjamin-6-11
            
            
            
            
            
            
